# Generated by Django 4.2.3 on 2023-07-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.URLField(),
        ),
    ]
