# Generated by Django 4.2.3 on 2023-07-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_vacancies_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='tags',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
