# Generated by Django 4.2.3 on 2023-08-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_tasks_tasksfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='answer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
