# Generated by Django 4.2.3 on 2023-08-02 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_taskcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksfiles',
            name='task_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='base.tasks'),
        ),
    ]
